### ISSUE TITLE
FileNotFoundException bei Start

### ISSUE THREAD

**Issue by gianperrone** [ProPra16/programmierpraktikum-abschlussprojekt-let-s-play-propra#1]
Beim Ausführen der Main aus IntelliJ:

Unable to find config.txt: java.io.FileNotFoundException: /home/gian/Propra/abschluss/programmierpraktikum-abschlussprojekt-let-s-play-propra/build/build/libs/config/config.txt (Datei oder Verzeichnis nicht gefunden)

Das Problem liegt in der getCorrectPath(), bei mir landet ein "build/" zu viel im Pfad

**Comment by ViktorKoenigsmann** [comment]
Das Problem existiert nicht mehr, wenn man die jar ausführt. Ich versuche es aber dennoch gleich zu beheben, sodass getcorrectpath in jar und main funktioniert . 
MfG 
Am 12.07.2016 2:42 nachm. schrieb Gian Perrone notifications@github.com:Beim Ausführen der Main aus IntelliJ:

Unable to find config.txt: java.io.FileNotFoundException: /home/gian/Propra/abschluss/programmierpraktikum-abschlussprojekt-let-s-play-propra/build/build/libs/config/config.txt (Datei oder Verzeichnis nicht gefunden)

Das Problem liegt in der getCorrectPath(), bei mir landet ein "build/" zu viel im Pfad

**Comment by FreddyGries** [comment]
Das Programm so wie es ist klappt momentan nur, wenn man es mit der Gradle Datei baut und dann die erstellte .jar ausführt. Einen Weg, wie beide Varianten gleichzeitig funktionieren haben wir bis lang nicht gefunden. Das laden der FXML-Dateien via getResource funktioniert in beiden Varianten, aber das nur ein InputStream ist, wüsste ich keine Variante wie man dorthin schreiben kann
