### ISSUE TITLE
Bei nicht kompilierbarem Test muss man nach Grün wechseln können

### ISSUE THREAD

**Issue by gianperrone** [ProPra16/programmierpraktikum-abschlussprojekt-let-s-play-propra#3]
Ich zitiere mal aus der Aufgabenstellung:
Wenn man den ersten Test für eine Methode schreibt, existiert die Methode noch nicht. Folglich kann der Test nicht kompiliert werden

Ich kann keinen Test schreiben, der fehlschlägt und kompiliert, wenn die zu testende Methode noch nicht existiert. Das müsst ihr bitte noch nachbessern.

**Comment by FreddyGries** [comment]
Fixed.

Auch wenn es mir so etwas komisch erscheint, ist jetzt zumindest die geforderte Eigenschaft vorhanden. Auch bei nicht kompilierbaren Tests kann jetzt gewechselt werden..
